---
getwd(title: "ML project"
output: html_document
date: "2025-02-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("/Users/cindyyu/Desktop/CS4220")
library(readxl)
library(tidyverse)

#random forest
library(dplyr)
```

#READING IN FILTER PREDICTIONS
```{r}
real1_df <- read.table("snv-parse-real1.txt", header = T)
real2.1_df <- read.table("snv-parse-real2_part1.txt", header = T)
syn1_df <- read.table("snv-parse-syn1.txt", header = T)
syn2_df <- read.table("snv-parse-syn2.txt", header = T)
syn3_df <- read.table("snv-parse-syn3.txt", header = T)
syn4_df <- read.table("snv-parse-syn4.txt", header = T)
syn5_df <- read.table("snv-parse-syn5.txt", header = T)

all_df <- rbind(real1_df, real2.1_df, syn1_df, syn2_df, syn3_df, syn4_df, syn5_df)
```

#READING IN TRUTHS

```{r}
#add headers: chromosome #, genomic start, genomic stop
real1_truth <- as.data.frame(read.table("/Users/cindyyu/Desktop/CS4220/Data/real1/real1_truth.bed",
                                header = FALSE, sep="\t",stringsAsFactors=FALSE, quote=""))
real2.1_truth <- as.data.frame(read.table("/Users/cindyyu/Desktop/CS4220/Data/real2_part1/real2_truth_chr1to5.bed",
                                header = FALSE, sep="\t",stringsAsFactors=FALSE, quote=""))
syn1_truth <- as.data.frame(read.table("/Users/cindyyu/Desktop/CS4220/Data/syn1/syn1_truth.bed",
                                header = FALSE, sep="\t",stringsAsFactors=FALSE, quote=""))
syn2_truth <- as.data.frame(read.table("/Users/cindyyu/Desktop/CS4220/Data/syn2/syn2_truth.bed",
                                header = FALSE, sep="\t",stringsAsFactors=FALSE, quote=""))
syn3_truth <- as.data.frame(read.table("/Users/cindyyu/Desktop/CS4220/Data/syn3/syn3_truth.bed",
                                header = FALSE, sep="\t",stringsAsFactors=FALSE, quote=""))
syn4_truth <- as.data.frame(read.table("/Users/cindyyu/Desktop/CS4220/Data/syn4/syn4_truth.bed",
                                header = FALSE, sep="\t",stringsAsFactors=FALSE, quote=""))
syn5_truth <- as.data.frame(read.table("/Users/cindyyu/Desktop/CS4220/Data/syn5/syn5_truth.bed",
                                header = FALSE, sep="\t",stringsAsFactors=FALSE, quote=""))
alltruth_df <- rbind(real1_truth, real2.1_truth, syn1_truth, syn2_truth, syn3_truth, syn4_truth, syn5_truth)

#names(alltruth_df) <- c("Chr", "START_POS_REF", "END_POS_REF")

#write.table(alltruth_df, "all_truths.bed",row.names = F,col.names = F, sep="\t", quote=FALSE)
```


```{r}
jointruth<- function(truthdf, predsdf) {
  names(truthdf) <- c("Chr", "START_POS_REF", "END_POS_REF")
  truthdf$TRUTH = TRUE
  newdf <- predsdf %>% 
    left_join(truthdf, by=c('Chr','START_POS_REF', 'END_POS_REF'))
  newdf$TRUTH <- replace_na(newdf$TRUTH, FALSE)
  return(newdf)
}


#joins for vcfs and truths
df3 <- jointruth(alltruth_df, all_df)
# real1_df <- jointruth(real1_truth, real1_df)
# real2.1_df <- jointruth(real2.1_truth, real2.1_df)
# syn1_df <- jointruth(syn1_truth, syn1_df)
# syn2_df <- jointruth(syn2_truth, syn2_df)
# syn3_df <- jointruth(syn3_truth, syn3_df)
# syn4_df <- jointruth(syn4_truth, syn4_df)
# syn5_df <- jointruth(syn5_truth, syn5_df)


```

#CREATING BENCHMARKS 

## consensus between at least 2
```{r}
#F1 = 0.02754307
vcfs_list <- list(real1_df, real2.1_df, syn1_df, syn2_df, syn3_df, syn4_df, syn5_df)

consensus_predict <- function(df){
  consensus_df <- df |>
    mutate(two_plus = rowSums(select(., FILTER_Mutect2, FILTER_Freebayes, FILTER_Varscan, FILTER_Vardict)) >= 2) |>
    filter(two_plus == TRUE)
  consensus_predictions <- consensus_df[, -4]
  return(consensus_predictions)
}

#urgh loops arent working not worth it
consensus_real1 <- consensus_predict(real1_df)
consensus_real2.1 <- consensus_predict(real2.1_df)
consensus_syn1 <- consensus_predict(syn1_df)
consensus_syn2 <- consensus_predict(syn2_df)
consensus_syn3 <- consensus_predict(syn3_df)
consensus_syn4 <- consensus_predict(syn4_df)
consensus_syn5 <- consensus_predict(syn5_df)

write.table(consensus_real1, "consensus_real1.bed",row.names = F,col.names = F, sep="\t", quote=FALSE) 
write.table(consensus_real2.1, "consensus_real2.1.bed",row.names = F,col.names = F, sep="\t", quote=FALSE) 
write.table(consensus_syn1, "consensus_syn1.bed",row.names = F,col.names = F, sep="\t", quote=FALSE) 
write.table(consensus_syn2, "consensus_syn2.bed",row.names = F,col.names = F, sep="\t", quote=FALSE) 
write.table(consensus_syn3, "consensus_syn3.bed",row.names = F,col.names = F, sep="\t", quote=FALSE) 
write.table(consensus_syn4, "consensus_syn4.bed",row.names = F,col.names = F, sep="\t", quote=FALSE) 
write.table(consensus_syn5, "consensus_syn5.bed",row.names = F,col.names = F, sep="\t", quote=FALSE) 

```

## find best languages
```{r}
#MUTECT2 F1 = 0.79
m2_predictions <- all_df |>
  filter(FILTER_Mutect2)

write.table(m2_predictions, "my-m2-predictions.bed",row.names = F,col.names = F, sep="\t", quote=FALSE)

#FREEBAYES F1 = 0.75
f_predictions <- all_df |>
  filter(FILTER_Freebayes)

write.table(f_predictions, "my-f-predictions.bed",row.names = F,col.names = F, sep="\t", quote=FALSE)

#VARDICT F1 = 0.767
vd_predictions <- all_df |>
  filter(FILTER_Vardict)

write.table(vd_predictions, "my-vd-predictions.bed",row.names = F,col.names = F, sep="\t", quote=FALSE)

#VARSCAN = 0.337
vs_predictions <- all_df |>
  filter(FILTER_Varscan)

write.table(vs_predictions, "my-vs-predictions.bed",row.names = F,col.names = F, sep="\t", quote=FALSE)
```

## CONSENSUS BETWEEN VARDICT AND MUTECT2, THE BEST ONES
```{r}
best_two_predict <- function(df){
  new_df <- df |> 
    filter(FILTER_Mutect2 == TRUE & FILTER_Vardict == TRUE)
  return(new_df)
}

#F1 = 0.927

best_two_real1 <- best_two_predict(real1_df)
best_two_real2.1 <- best_two_predict(real2.1_df)
best_two_syn1 <- best_two_predict(syn1_df)
best_two_syn2 <- best_two_predict(syn2_df)
best_two_syn3 <- best_two_predict(syn3_df)
best_two_syn4 <- best_two_predict(syn4_df)
best_two_syn5 <- best_two_predict(syn5_df)


write.table(best_two_real1, "best_two_real1.bed",row.names = F,col.names = F, sep="\t", quote=FALSE) 
write.table(best_two_real2.1, "best_two_real2.1.bed",row.names = F,col.names = F, sep="\t", quote=FALSE) 
write.table(best_two_syn1, "best_two_syn1.bed",row.names = F,col.names = F, sep="\t", quote=FALSE) 
write.table(best_two_syn2, "best_two_syn2.bed",row.names = F,col.names = F, sep="\t", quote=FALSE) 
write.table(best_two_syn3, "best_two_syn3.bed",row.names = F,col.names = F, sep="\t", quote=FALSE) 
write.table(best_two_syn4, "best_two_syn4.bed",row.names = F,col.names = F, sep="\t", quote=FALSE) 
write.table(best_two_syn5, "best_two_syn5.bed",row.names = F,col.names = F, sep="\t", quote=FALSE) 
```


